name-template: 'v$RESOLVED_VERSION ğŸŒˆ'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸ¯ ìƒˆë¡œìš´ ê¸°ëŠ¥ì´ ì¶”ê°€ë˜ì—ˆì–´ìš”'
    labels: ['feat ğŸ¯']
  - title: 'ğŸ› ï¸ ê¸°ì¡´ ë²„ê·¸ê°€ ìˆ˜ì •ë˜ì—ˆì–´ìš”'
    labels:
      - 'fix ğŸ› ï¸'
      - 'HOTFIX ğŸš‘'
  - title: 'ğŸ¬ ì½”ë“œë¥¼ ê°œì„ í–ˆì–´ìš”'
    labels:
      - 'refactor ğŸ”'
      - 'test ğŸ§ª'
      - 'chore ğŸ”'
  - title: 'âš™ï¸ í”„ë¡œì íŠ¸ë¥¼ ê°œì„ í–ˆì–´ìš”'
    labels:
      - 'rename ğŸ“›'
      - 'remove ğŸ‘»'
      - 'docs âœğŸ»'
  - title: 'ğŸš€ ë°°í¬'
    labels:
      - 'deploy ğŸš€'

change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## ì´ë²ˆ ë²„ì „ì˜ ë³€ê²½ì‚¬í•­ì€ ì•„ë˜ì™€ ê°™ì•„ìš”
  ---
  $CHANGES
no-changes-template: 'ë³€ê²½ì‚¬í•­ì´ ì—†ì–´ìš”'
version-resolver:
  major:
    labels:
      - '1ï¸âƒ£ major'
  minor:
    labels:
      - '2ï¸âƒ£ minor'
  patch:
    labels:
      - '3ï¸âƒ£ patch'
  default: patch
